### ISSUE TITLE
DotenvAzure is not a contructor

### ISSUE THREAD

**Issue by MaheshSasidharan** [jazida-opensource/dotenv-azure#62]
The documentation says that `require('dotenv-azure')` returns a class. 
`const DotenvAzure = require('dotenv-azure');`

But I was getting 
>  TypeError: DotenvAzure is not a constructor

After going through the code, I realized that it returned an object with a property **DotenvAzure**.
So after changing it to retrieve the class property, I was able to get it to work.

`const { DotenvAzure } = require('dotenv-azure');
const dotenvAzure = new DotenvAzure();
`

Should the documentation be updated?

**Comment by danielfsousa** [comment]
Yes, this was a mistake

https://github.com/jazida-opensource/dotenv-azure/pull/67 should fix the code examples

**Comment by danielfsousa** [comment]
@all-contributors please add @MaheshSasidharan for doc
